//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string TacGia { get; set; }
        public string NXB { get; set; }
        public double DonGia { get; set; }
        public string MoTa { get; set; }
        public int SoLuong { get; set; }
        public int SoTrang { get; set; }
        public string TrongLuong { get; set; }
        public string KichThuoc { get; set; }
        public string LoaiBia { get; set; }
        public string TrangThai { get; set; }
        public string ImagePath { get; set; }
        public int MaLoaiSP { get; set; }
    }
}
